/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.http.client;

import com.travelpayouts.api.controllers.BaseStreamController;

/**
 * Callback class for handling Streaming API calls with a templated response type T
 */
public interface APIStreamingCallBack<T> {
    /**
     * On data arrival callback, notifying that a new data response has arrived
     * @param source    The source of the API stream
     * @param data      The response received from the API Call
     */
    public void onDataArrival(BaseStreamController<T> source, T data);
    
    /**
     * On stream closed callback, notifying that the underlying stream has closed
     * @param source    The source of the API stream
     */
    public void onStreamClosed(BaseStreamController<T> source);
    
    /**
     * On Completed callback for API calls
     * @param source   The source of the API stream, which ran into exception
     * @param error Any error detected during the API call, streaming and/or deserialization
     */
    public void onFailure(HttpContext context, Throwable error);
}