/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class AirlineDataInJsonFormatModelBuilder {
    //the instance to build
    private AirlineDataInJsonFormatModel airlineDataInJsonFormatModel;

    /**
     * Default constructor to initialize the instance
     */
    public AirlineDataInJsonFormatModelBuilder() {
        airlineDataInJsonFormatModel = new AirlineDataInJsonFormatModel();
    }

    /**
     * airline name
     */
    public AirlineDataInJsonFormatModelBuilder name(String name) {
        airlineDataInJsonFormatModel.setName(name);
        return this;
    }

    /**
     * alliance name (if the airline is an alliance member)
     */
    public AirlineDataInJsonFormatModelBuilder alias(String alias) {
        airlineDataInJsonFormatModel.setAlias(alias);
        return this;
    }

    /**
     * airline IATA code
     */
    public AirlineDataInJsonFormatModelBuilder iata(String iata) {
        airlineDataInJsonFormatModel.setIata(iata);
        return this;
    }

    /**
     * airline ICAO code
     */
    public AirlineDataInJsonFormatModelBuilder icao(String icao) {
        airlineDataInJsonFormatModel.setIcao(icao);
        return this;
    }

    /**
     * airline call sign
     */
    public AirlineDataInJsonFormatModelBuilder callsign(String callsign) {
        airlineDataInJsonFormatModel.setCallsign(callsign);
        return this;
    }

    /**
     * airline country of registration
     */
    public AirlineDataInJsonFormatModelBuilder country(String country) {
        airlineDataInJsonFormatModel.setCountry(country);
        return this;
    }

    /**
     * true: company is active, false: company is not active
     */
    public AirlineDataInJsonFormatModelBuilder isActive(boolean isActive) {
        airlineDataInJsonFormatModel.setIsActive(isActive);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AirlineDataInJsonFormatModel build() {
        return airlineDataInJsonFormatModel;
    }
}