/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AirlineDataInJsonFormatModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5458597616224524716L;
    private String name;
    private String alias;
    private String iata;
    private String icao;
    private String callsign;
    private String country;
    private boolean isActive;
    /** GETTER
     * airline name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * airline name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * alliance name (if the airline is an alliance member)
     */
    @JsonGetter("alias")
    public String getAlias ( ) { 
        return this.alias;
    }
    
    /** SETTER
     * alliance name (if the airline is an alliance member)
     */
    @JsonSetter("alias")
    public void setAlias (String value) { 
        this.alias = value;
    }
 
    /** GETTER
     * airline IATA code
     */
    @JsonGetter("iata")
    public String getIata ( ) { 
        return this.iata;
    }
    
    /** SETTER
     * airline IATA code
     */
    @JsonSetter("iata")
    public void setIata (String value) { 
        this.iata = value;
    }
 
    /** GETTER
     * airline ICAO code
     */
    @JsonGetter("icao")
    public String getIcao ( ) { 
        return this.icao;
    }
    
    /** SETTER
     * airline ICAO code
     */
    @JsonSetter("icao")
    public void setIcao (String value) { 
        this.icao = value;
    }
 
    /** GETTER
     * airline call sign
     */
    @JsonGetter("callsign")
    public String getCallsign ( ) { 
        return this.callsign;
    }
    
    /** SETTER
     * airline call sign
     */
    @JsonSetter("callsign")
    public void setCallsign (String value) { 
        this.callsign = value;
    }
 
    /** GETTER
     * airline country of registration
     */
    @JsonGetter("country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * airline country of registration
     */
    @JsonSetter("country")
    public void setCountry (String value) { 
        this.country = value;
    }
 
    /** GETTER
     * true: company is active, false: company is not active
     */
    @JsonGetter("is_active")
    public boolean getIsActive ( ) { 
        return this.isActive;
    }
    
    /** SETTER
     * true: company is active, false: company is not active
     */
    @JsonSetter("is_active")
    public void setIsActive (boolean value) { 
        this.isActive = value;
    }
 
}
 