/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AirportDataInJsonFormatModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4864413567065401435L;
    private String code;
    private String name;
    private LinkedHashMap<String, AirportDataInJsonFormatCoordinatesModel> coordinates;
    private String timeZone;
    private LinkedHashMap<String, String> nameTranslations;
    private String countryCode;
    private String cityCode;
    /** GETTER
     * airport IATA code
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * airport IATA code
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * airport name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * airport name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * airport longitude and latitude
     */
    @JsonGetter("coordinates")
    public LinkedHashMap<String, AirportDataInJsonFormatCoordinatesModel> getCoordinates ( ) { 
        return this.coordinates;
    }
    
    /** SETTER
     * airport longitude and latitude
     */
    @JsonSetter("coordinates")
    public void setCoordinates (LinkedHashMap<String, AirportDataInJsonFormatCoordinatesModel> value) { 
        this.coordinates = value;
    }
 
    /** GETTER
     * time zone relative to GMT
     */
    @JsonGetter("time_zone")
    public String getTimeZone ( ) { 
        return this.timeZone;
    }
    
    /** SETTER
     * time zone relative to GMT
     */
    @JsonSetter("time_zone")
    public void setTimeZone (String value) { 
        this.timeZone = value;
    }
 
    /** GETTER
     * the name of the airport in different languages
     */
    @JsonGetter("name_translations")
    public LinkedHashMap<String, String> getNameTranslations ( ) { 
        return this.nameTranslations;
    }
    
    /** SETTER
     * the name of the airport in different languages
     */
    @JsonSetter("name_translations")
    public void setNameTranslations (LinkedHashMap<String, String> value) { 
        this.nameTranslations = value;
    }
 
    /** GETTER
     * country IATA code
     */
    @JsonGetter("country_code")
    public String getCountryCode ( ) { 
        return this.countryCode;
    }
    
    /** SETTER
     * country IATA code
     */
    @JsonSetter("country_code")
    public void setCountryCode (String value) { 
        this.countryCode = value;
    }
 
    /** GETTER
     * city IATA code
     */
    @JsonGetter("city_code")
    public String getCityCode ( ) { 
        return this.cityCode;
    }
    
    /** SETTER
     * city IATA code
     */
    @JsonSetter("city_code")
    public void setCityCode (String value) { 
        this.cityCode = value;
    }
 
}
 