/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AirplaneDataInJsonFormatModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4842585240413821947L;
    private String code;
    private String name;
    /** GETTER
     * plane IATA code
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * plane IATA code
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * plane name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * plane name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
}
 