/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AllianceDataInJsonFormatModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4660204391072351058L;
    private String name;
    private List<String> airlines;
    /** GETTER
     * alliance name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * alliance name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * codes for alliance member companies
     */
    @JsonGetter("airlines")
    public List<String> getAirlines ( ) { 
        return this.airlines;
    }
    
    /** SETTER
     * codes for alliance member companies
     */
    @JsonSetter("airlines")
    public void setAirlines (List<String> value) { 
        this.airlines = value;
    }
 
}
 