/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class AllianceDataInJsonFormatModelBuilder {
    //the instance to build
    private AllianceDataInJsonFormatModel allianceDataInJsonFormatModel;

    /**
     * Default constructor to initialize the instance
     */
    public AllianceDataInJsonFormatModelBuilder() {
        allianceDataInJsonFormatModel = new AllianceDataInJsonFormatModel();
    }

    /**
     * alliance name
     */
    public AllianceDataInJsonFormatModelBuilder name(String name) {
        allianceDataInJsonFormatModel.setName(name);
        return this;
    }

    /**
     * codes for alliance member companies
     */
    public AllianceDataInJsonFormatModelBuilder airlines(List<String> airlines) {
        allianceDataInJsonFormatModel.setAirlines(airlines);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AllianceDataInJsonFormatModel build() {
        return allianceDataInJsonFormatModel;
    }
}