/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class CheapestTicketsDataModelBuilder 
        extends CheapestTicketsModelBuilder {
    //the instance to build
    private CheapestTicketsDataModel cheapestTicketsDataModel;

    /**
     * Default constructor to initialize the instance
     */
    public CheapestTicketsDataModelBuilder() {
        cheapestTicketsDataModel = new CheapestTicketsDataModel();
    }

    /**
     * IATA code of the destination city
     */
    public CheapestTicketsDataModelBuilder hKT(LinkedHashMap<String, Object> hKT) {
        cheapestTicketsDataModel.setHKT(hKT);
        return this;
    }

    /**
     * ticket price (in the currency specified in the currency parameter)
     */
    public CheapestTicketsDataModelBuilder price(int price) {
        cheapestTicketsDataModel.setPrice(price);
        return this;
    }

    /**
     * IATA code of the airline operating the flight
     */
    public CheapestTicketsDataModelBuilder airline(String airline) {
        cheapestTicketsDataModel.setAirline(airline);
        return this;
    }

    /**
     * flight number
     */
    public CheapestTicketsDataModelBuilder flightNumber(int flightNumber) {
        cheapestTicketsDataModel.setFlightNumber(flightNumber);
        return this;
    }

    /**
     * departure date
     */
    public CheapestTicketsDataModelBuilder departureAt(String departureAt) {
        cheapestTicketsDataModel.setDepartureAt(departureAt);
        return this;
    }

    /**
     * return date
     */
    public CheapestTicketsDataModelBuilder returnAt(String returnAt) {
        cheapestTicketsDataModel.setReturnAt(returnAt);
        return this;
    }

    /**
     * date on which the found price expires (UTC+0)
     */
    public CheapestTicketsDataModelBuilder expiresAt(String expiresAt) {
        cheapestTicketsDataModel.setExpiresAt(expiresAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CheapestTicketsDataModel build() {
        return cheapestTicketsDataModel;
    }
}