/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class CheapestTicketsModelBuilder {
    //the instance to build
    private CheapestTicketsModel cheapestTicketsModel;

    /**
     * Default constructor to initialize the instance
     */
    public CheapestTicketsModelBuilder() {
        cheapestTicketsModel = new CheapestTicketsModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public CheapestTicketsModelBuilder success(boolean success) {
        cheapestTicketsModel.setSuccess(success);
        return this;
    }

    /**
     * data of response
     */
    public CheapestTicketsModelBuilder data(LinkedHashMap<String, CheapestTicketsDataModel> data) {
        cheapestTicketsModel.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CheapestTicketsModel build() {
        return cheapestTicketsModel;
    }
}