/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CheapestTicketsDataModel 
        extends CheapestTicketsModel {
    private static final long serialVersionUID = 5075646884624797849L;
    private LinkedHashMap<String, Object> hKT;
    private int price;
    private String airline;
    private int flightNumber;
    private String departureAt;
    private String returnAt;
    private String expiresAt;
    /** GETTER
     * IATA code of the destination city
     */
    @JsonGetter("HKT")
    public LinkedHashMap<String, Object> getHKT ( ) { 
        return this.hKT;
    }
    
    /** SETTER
     * IATA code of the destination city
     */
    @JsonSetter("HKT")
    public void setHKT (LinkedHashMap<String, Object> value) { 
        this.hKT = value;
    }
 
    /** GETTER
     * ticket price (in the currency specified in the currency parameter)
     */
    @JsonGetter("price")
    public int getPrice ( ) { 
        return this.price;
    }
    
    /** SETTER
     * ticket price (in the currency specified in the currency parameter)
     */
    @JsonSetter("price")
    public void setPrice (int value) { 
        this.price = value;
    }
 
    /** GETTER
     * IATA code of the airline operating the flight
     */
    @JsonGetter("airline")
    public String getAirline ( ) { 
        return this.airline;
    }
    
    /** SETTER
     * IATA code of the airline operating the flight
     */
    @JsonSetter("airline")
    public void setAirline (String value) { 
        this.airline = value;
    }
 
    /** GETTER
     * flight number
     */
    @JsonGetter("flight_number")
    public int getFlightNumber ( ) { 
        return this.flightNumber;
    }
    
    /** SETTER
     * flight number
     */
    @JsonSetter("flight_number")
    public void setFlightNumber (int value) { 
        this.flightNumber = value;
    }
 
    /** GETTER
     * departure date
     */
    @JsonGetter("departure_at")
    public String getDepartureAt ( ) { 
        return this.departureAt;
    }
    
    /** SETTER
     * departure date
     */
    @JsonSetter("departure_at")
    public void setDepartureAt (String value) { 
        this.departureAt = value;
    }
 
    /** GETTER
     * return date
     */
    @JsonGetter("return_at")
    public String getReturnAt ( ) { 
        return this.returnAt;
    }
    
    /** SETTER
     * return date
     */
    @JsonSetter("return_at")
    public void setReturnAt (String value) { 
        this.returnAt = value;
    }
 
    /** GETTER
     * date on which the found price expires (UTC+0)
     */
    @JsonGetter("expires_at")
    public String getExpiresAt ( ) { 
        return this.expiresAt;
    }
    
    /** SETTER
     * date on which the found price expires (UTC+0)
     */
    @JsonSetter("expires_at")
    public void setExpiresAt (String value) { 
        this.expiresAt = value;
    }
 
}
 