/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class CityDataInJsonFormatCoordinatesModelBuilder 
        extends CityDataInJsonFormatModelBuilder {
    //the instance to build
    private CityDataInJsonFormatCoordinatesModel cityDataInJsonFormatCoordinatesModel;

    /**
     * Default constructor to initialize the instance
     */
    public CityDataInJsonFormatCoordinatesModelBuilder() {
        cityDataInJsonFormatCoordinatesModel = new CityDataInJsonFormatCoordinatesModel();
    }

    /**
     * citie longitude
     */
    public CityDataInJsonFormatCoordinatesModelBuilder lon(double lon) {
        cityDataInJsonFormatCoordinatesModel.setLon(lon);
        return this;
    }

    /**
     * citie latitude
     */
    public CityDataInJsonFormatCoordinatesModelBuilder lat(double lat) {
        cityDataInJsonFormatCoordinatesModel.setLat(lat);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CityDataInJsonFormatCoordinatesModel build() {
        return cityDataInJsonFormatCoordinatesModel;
    }
}