/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class CityDataInJsonFormatModelBuilder {
    //the instance to build
    private CityDataInJsonFormatModel cityDataInJsonFormatModel;

    /**
     * Default constructor to initialize the instance
     */
    public CityDataInJsonFormatModelBuilder() {
        cityDataInJsonFormatModel = new CityDataInJsonFormatModel();
    }

    /**
     * city IATA-code
     */
    public CityDataInJsonFormatModelBuilder code(String code) {
        cityDataInJsonFormatModel.setCode(code);
        return this;
    }

    /**
     * city name
     */
    public CityDataInJsonFormatModelBuilder name(String name) {
        cityDataInJsonFormatModel.setName(name);
        return this;
    }

    /**
     * city coordinates
     */
    public CityDataInJsonFormatModelBuilder coordinates(LinkedHashMap<String, CityDataInJsonFormatCoordinatesModel> coordinates) {
        cityDataInJsonFormatModel.setCoordinates(coordinates);
        return this;
    }

    /**
     * timezone relative to GMT
     */
    public CityDataInJsonFormatModelBuilder timeZone(String timeZone) {
        cityDataInJsonFormatModel.setTimeZone(timeZone);
        return this;
    }

    /**
     * translation of city name
     */
    public CityDataInJsonFormatModelBuilder nameTranslations(LinkedHashMap<String, String> nameTranslations) {
        cityDataInJsonFormatModel.setNameTranslations(nameTranslations);
        return this;
    }

    /**
     * country IATA-code
     */
    public CityDataInJsonFormatModelBuilder countryCode(String countryCode) {
        cityDataInJsonFormatModel.setCountryCode(countryCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CityDataInJsonFormatModel build() {
        return cityDataInJsonFormatModel;
    }
}