/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CityDataInJsonFormatCoordinatesModel 
        extends CityDataInJsonFormatModel {
    private static final long serialVersionUID = 5379041415187618365L;
    private double lon;
    private double lat;
    /** GETTER
     * citie longitude
     */
    @JsonGetter("lon")
    public double getLon ( ) { 
        return this.lon;
    }
    
    /** SETTER
     * citie longitude
     */
    @JsonSetter("lon")
    public void setLon (double value) { 
        this.lon = value;
    }
 
    /** GETTER
     * citie latitude
     */
    @JsonGetter("lat")
    public double getLat ( ) { 
        return this.lat;
    }
    
    /** SETTER
     * citie latitude
     */
    @JsonSetter("lat")
    public void setLat (double value) { 
        this.lat = value;
    }
 
}
 