/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DataOfCountriesInJsonFormatModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4888154563561248875L;
    private String code;
    private String name;
    private String currency;
    private LinkedHashMap<String, String> nameTranslations;
    /** GETTER
     * IATA-code of country
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * IATA-code of country
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * country name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * country name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * currency country
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * currency country
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * translation of country name
     */
    @JsonGetter("name_translations")
    public LinkedHashMap<String, String> getNameTranslations ( ) { 
        return this.nameTranslations;
    }
    
    /** SETTER
     * translation of country name
     */
    @JsonSetter("name_translations")
    public void setNameTranslations (LinkedHashMap<String, String> value) { 
        this.nameTranslations = value;
    }
 
}
 