/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class DataOfCountriesInJsonFormatModelBuilder {
    //the instance to build
    private DataOfCountriesInJsonFormatModel dataOfCountriesInJsonFormatModel;

    /**
     * Default constructor to initialize the instance
     */
    public DataOfCountriesInJsonFormatModelBuilder() {
        dataOfCountriesInJsonFormatModel = new DataOfCountriesInJsonFormatModel();
    }

    /**
     * IATA-code of country
     */
    public DataOfCountriesInJsonFormatModelBuilder code(String code) {
        dataOfCountriesInJsonFormatModel.setCode(code);
        return this;
    }

    /**
     * country name
     */
    public DataOfCountriesInJsonFormatModelBuilder name(String name) {
        dataOfCountriesInJsonFormatModel.setName(name);
        return this;
    }

    /**
     * currency country
     */
    public DataOfCountriesInJsonFormatModelBuilder currency(String currency) {
        dataOfCountriesInJsonFormatModel.setCurrency(currency);
        return this;
    }

    /**
     * translation of country name
     */
    public DataOfCountriesInJsonFormatModelBuilder nameTranslations(LinkedHashMap<String, String> nameTranslations) {
        dataOfCountriesInJsonFormatModel.setNameTranslations(nameTranslations);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DataOfCountriesInJsonFormatModel build() {
        return dataOfCountriesInJsonFormatModel;
    }
}