/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class GetNonStopTicketsInputBuilder {
    //the instance to build
    private GetNonStopTicketsInput getNonStopTicketsInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetNonStopTicketsInputBuilder() {
        getNonStopTicketsInput = new GetNonStopTicketsInput();
    }

    /**
     * The airline tickets currency.
     */
    public GetNonStopTicketsInputBuilder currency(String currency) {
        getNonStopTicketsInput.setCurrency(currency);
        return this;
    }

    /**
     * IATA code of departure city. IATA code is shown by uppercase letters, for example MOW.
     */
    public GetNonStopTicketsInputBuilder origin(String origin) {
        getNonStopTicketsInput.setOrigin(origin);
        return this;
    }

    /**
     * Day or month of departure (yyyy-mm-dd or yyyy-mm).
     */
    public GetNonStopTicketsInputBuilder departDate(Date departDate) {
        getNonStopTicketsInput.setDepartDate(departDate);
        return this;
    }

    /**
     * Day or month of return (yyyy-mm-dd or yyyy-mm).
     */
    public GetNonStopTicketsInputBuilder returnDate(Date returnDate) {
        getNonStopTicketsInput.setReturnDate(returnDate);
        return this;
    }

    /**
     * IATA code of destination city (for all routes, enter “-”). IATA code is shown by uppercase letters, for example MOW.
     */
    public GetNonStopTicketsInputBuilder destination(String destination) {
        getNonStopTicketsInput.setDestination(destination);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetNonStopTicketsInput build() {
        return getNonStopTicketsInput;
    }
}