/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetNonStopTicketsInput 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5583921024180165341L;
    private String currency = "RUB";
    private String origin = "HKT";
    private Date departDate;
    private Date returnDate;
    private String destination;
    /** GETTER
     * The airline tickets currency.
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * The airline tickets currency.
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * IATA code of departure city. IATA code is shown by uppercase letters, for example MOW.
     */
    @JsonGetter("origin")
    public String getOrigin ( ) { 
        return this.origin;
    }
    
    /** SETTER
     * IATA code of departure city. IATA code is shown by uppercase letters, for example MOW.
     */
    @JsonSetter("origin")
    public void setOrigin (String value) { 
        this.origin = value;
    }
 
    /** GETTER
     * Day or month of departure (yyyy-mm-dd or yyyy-mm).
     */
    @JsonGetter("depart_date")
    public Date getDepartDate ( ) { 
        return this.departDate;
    }
    
    /** SETTER
     * Day or month of departure (yyyy-mm-dd or yyyy-mm).
     */
    @JsonSetter("depart_date")
    public void setDepartDate (Date value) { 
        this.departDate = value;
    }
 
    /** GETTER
     * Day or month of return (yyyy-mm-dd or yyyy-mm).
     */
    @JsonGetter("return_date")
    public Date getReturnDate ( ) { 
        return this.returnDate;
    }
    
    /** SETTER
     * Day or month of return (yyyy-mm-dd or yyyy-mm).
     */
    @JsonSetter("return_date")
    public void setReturnDate (Date value) { 
        this.returnDate = value;
    }
 
    /** GETTER
     * IATA code of destination city (for all routes, enter “-”). IATA code is shown by uppercase letters, for example MOW.
     */
    @JsonGetter("destination")
    public String getDestination ( ) { 
        return this.destination;
    }
    
    /** SETTER
     * IATA code of destination city (for all routes, enter “-”). IATA code is shown by uppercase letters, for example MOW.
     */
    @JsonSetter("destination")
    public void setDestination (String value) { 
        this.destination = value;
    }
 
}
 