/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class GetPopularAirlineRoutesInputBuilder {
    //the instance to build
    private GetPopularAirlineRoutesInput getPopularAirlineRoutesInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetPopularAirlineRoutesInputBuilder() {
        getPopularAirlineRoutesInput = new GetPopularAirlineRoutesInput();
    }

    /**
     * IATA code of airline
     */
    public GetPopularAirlineRoutesInputBuilder airlineCode(String airlineCode) {
        getPopularAirlineRoutesInput.setAirlineCode(airlineCode);
        return this;
    }

    /**
     * records limit per page. Default value is 100. Not less than 1000
     */
    public GetPopularAirlineRoutesInputBuilder limit(String limit) {
        getPopularAirlineRoutesInput.setLimit(limit);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetPopularAirlineRoutesInput build() {
        return getPopularAirlineRoutesInput;
    }
}