/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetPopularAirlineRoutesInput 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5522226576096744874L;
    private String airlineCode;
    private String limit = "100";
    /** GETTER
     * IATA code of airline
     */
    @JsonGetter("airline_code")
    public String getAirlineCode ( ) { 
        return this.airlineCode;
    }
    
    /** SETTER
     * IATA code of airline
     */
    @JsonSetter("airline_code")
    public void setAirlineCode (String value) { 
        this.airlineCode = value;
    }
 
    /** GETTER
     * records limit per page. Default value is 100. Not less than 1000
     */
    @JsonGetter("limit")
    public String getLimit ( ) { 
        return this.limit;
    }
    
    /** SETTER
     * records limit per page. Default value is 100. Not less than 1000
     */
    @JsonSetter("limit")
    public void setLimit (String value) { 
        this.limit = value;
    }
 
}
 