/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class GetThePopularDirectionsFromACityInputBuilder {
    //the instance to build
    private GetThePopularDirectionsFromACityInput getThePopularDirectionsFromACityInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetThePopularDirectionsFromACityInputBuilder() {
        getThePopularDirectionsFromACityInput = new GetThePopularDirectionsFromACityInput();
    }

    /**
     * the point of departure. The IATA city code or the country code. The length - from 2 to 3 symbols.
     */
    public GetThePopularDirectionsFromACityInputBuilder origin(String origin) {
        getThePopularDirectionsFromACityInput.setOrigin(origin);
        return this;
    }

    /**
     * the airline tickets currency
     */
    public GetThePopularDirectionsFromACityInputBuilder currency(String currency) {
        getThePopularDirectionsFromACityInput.setCurrency(currency);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetThePopularDirectionsFromACityInput build() {
        return getThePopularDirectionsFromACityInput;
    }
}