/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetTheCalendarOfPricesForAWeekInput 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4913835179963877287L;
    private String currency = "RUB";
    private String origin;
    private String destination;
    private Date departDate;
    private Date returnDate;
    private Boolean showToAffiliates = true;
    /** GETTER
     * the airline tickets currency
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * the airline tickets currency
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * the point of departure. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonGetter("origin")
    public String getOrigin ( ) { 
        return this.origin;
    }
    
    /** SETTER
     * the point of departure. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonSetter("origin")
    public void setOrigin (String value) { 
        this.origin = value;
    }
 
    /** GETTER
     * the point of destination. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonGetter("destination")
    public String getDestination ( ) { 
        return this.destination;
    }
    
    /** SETTER
     * the point of destination. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonSetter("destination")
    public void setDestination (String value) { 
        this.destination = value;
    }
 
    /** GETTER
     * day or month of departure (yyyy-mm-dd or yyyy-mm)
     */
    @JsonGetter("depart_date")
    public Date getDepartDate ( ) { 
        return this.departDate;
    }
    
    /** SETTER
     * day or month of departure (yyyy-mm-dd or yyyy-mm)
     */
    @JsonSetter("depart_date")
    public void setDepartDate (Date value) { 
        this.departDate = value;
    }
 
    /** GETTER
     * day or month of return (yyyy-mm-dd or yyyy-mm)
     */
    @JsonGetter("return_date")
    public Date getReturnDate ( ) { 
        return this.returnDate;
    }
    
    /** SETTER
     * day or month of return (yyyy-mm-dd or yyyy-mm)
     */
    @JsonSetter("return_date")
    public void setReturnDate (Date value) { 
        this.returnDate = value;
    }
 
    /** GETTER
     * false - all the prices, true - just the prices, found using the partner marker (recommended).
     */
    @JsonGetter("show_to_affiliates")
    public Boolean getShowToAffiliates ( ) { 
        return this.showToAffiliates;
    }
    
    /** SETTER
     * false - all the prices, true - just the prices, found using the partner marker (recommended).
     */
    @JsonSetter("show_to_affiliates")
    public void setShowToAffiliates (Boolean value) { 
        this.showToAffiliates = value;
    }
 
}
 