/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class GetTheCalendarOfPricesForAMonthInputBuilder {
    //the instance to build
    private GetTheCalendarOfPricesForAMonthInput getTheCalendarOfPricesForAMonthInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetTheCalendarOfPricesForAMonthInputBuilder() {
        getTheCalendarOfPricesForAMonthInput = new GetTheCalendarOfPricesForAMonthInput();
    }

    /**
     * the airline tickets currency
     */
    public GetTheCalendarOfPricesForAMonthInputBuilder currency(String currency) {
        getTheCalendarOfPricesForAMonthInput.setCurrency(currency);
        return this;
    }

    /**
     * the point of departure. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    public GetTheCalendarOfPricesForAMonthInputBuilder origin(String origin) {
        getTheCalendarOfPricesForAMonthInput.setOrigin(origin);
        return this;
    }

    /**
     * the point of destination. The IATA city code or the country code. The length - from 2 to 3 symbols. Note! If the point of departure and the point of destination are not specified, then the API shall bring 30 the most cheapest tickets, which have been found during the recent 48 hours, back.
     */
    public GetTheCalendarOfPricesForAMonthInputBuilder destination(String destination) {
        getTheCalendarOfPricesForAMonthInput.setDestination(destination);
        return this;
    }

    /**
     * the beginning of the month in the YYYY-MM-DD format
     */
    public GetTheCalendarOfPricesForAMonthInputBuilder month(String month) {
        getTheCalendarOfPricesForAMonthInput.setMonth(month);
        return this;
    }

    /**
     * false - все цены, true - только цены, найденные с партнёрским маркером (рекомендовано). Значение по умолчанию - true.
     */
    public GetTheCalendarOfPricesForAMonthInputBuilder showToAffiliates(Boolean showToAffiliates) {
        getTheCalendarOfPricesForAMonthInput.setShowToAffiliates(showToAffiliates);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetTheCalendarOfPricesForAMonthInput build() {
        return getTheCalendarOfPricesForAMonthInput;
    }
}