/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetThePricesForTheAlternativeDirectionsInput 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4672870434521172107L;
    private String currency = "RUB";
    private String origin;
    private String destination;
    private String departDate;
    private String returnDate;
    private Boolean showToAffiliates = true;
    private String limit;
    private String flexibility;
    private String distance;
    /** GETTER
     * the airline tickets currency
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * the airline tickets currency
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * the point of departure. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonGetter("origin")
    public String getOrigin ( ) { 
        return this.origin;
    }
    
    /** SETTER
     * the point of departure. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonSetter("origin")
    public void setOrigin (String value) { 
        this.origin = value;
    }
 
    /** GETTER
     * the point of destination. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonGetter("destination")
    public String getDestination ( ) { 
        return this.destination;
    }
    
    /** SETTER
     * the point of destination. The IATA city code or the country code. The length - from 2 to 3 symbols
     */
    @JsonSetter("destination")
    public void setDestination (String value) { 
        this.destination = value;
    }
 
    /** GETTER
     * day or month of departure (yyyy-mm-dd or yyyy-mm).
     */
    @JsonGetter("depart_date")
    public String getDepartDate ( ) { 
        return this.departDate;
    }
    
    /** SETTER
     * day or month of departure (yyyy-mm-dd or yyyy-mm).
     */
    @JsonSetter("depart_date")
    public void setDepartDate (String value) { 
        this.departDate = value;
    }
 
    /** GETTER
     * day or month of return (yyyy-mm-dd or yyyy-mm).
     */
    @JsonGetter("return_date")
    public String getReturnDate ( ) { 
        return this.returnDate;
    }
    
    /** SETTER
     * day or month of return (yyyy-mm-dd or yyyy-mm).
     */
    @JsonSetter("return_date")
    public void setReturnDate (String value) { 
        this.returnDate = value;
    }
 
    /** GETTER
     * false - all the prices, true - just the prices, found using the partner marker (recommended)
     */
    @JsonGetter("show_to_affiliates")
    public Boolean getShowToAffiliates ( ) { 
        return this.showToAffiliates;
    }
    
    /** SETTER
     * false - all the prices, true - just the prices, found using the partner marker (recommended)
     */
    @JsonSetter("show_to_affiliates")
    public void setShowToAffiliates (Boolean value) { 
        this.showToAffiliates = value;
    }
 
    /** GETTER
     * the number of variants entered, from 1 to 20. Where 1 – is just the variant with the specified points of departure and the points of destination
     */
    @JsonGetter("limit")
    public String getLimit ( ) { 
        return this.limit;
    }
    
    /** SETTER
     * the number of variants entered, from 1 to 20. Where 1 – is just the variant with the specified points of departure and the points of destination
     */
    @JsonSetter("limit")
    public void setLimit (String value) { 
        this.limit = value;
    }
 
    /** GETTER
     * expansion of the range of dates upward or downward. The value may vary from 0 to 7, where 0 shall show the variants for the dates specified, 7 – all the variants found for a week prior to the specified dates and a week after
     */
    @JsonGetter("flexibility")
    public String getFlexibility ( ) { 
        return this.flexibility;
    }
    
    /** SETTER
     * expansion of the range of dates upward or downward. The value may vary from 0 to 7, where 0 shall show the variants for the dates specified, 7 – all the variants found for a week prior to the specified dates and a week after
     */
    @JsonSetter("flexibility")
    public void setFlexibility (String value) { 
        this.flexibility = value;
    }
 
    /** GETTER
     * the number of variants entered, from 1 to 20. Where 1 – is just the variant with the specified points of departure and the points of destination
     */
    @JsonGetter("distance")
    public String getDistance ( ) { 
        return this.distance;
    }
    
    /** SETTER
     * the number of variants entered, from 1 to 20. Where 1 – is just the variant with the specified points of departure and the points of destination
     */
    @JsonSetter("distance")
    public void setDistance (String value) { 
        this.distance = value;
    }
 
}
 