/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class NonStopTicketsDataModelBuilder 
        extends NonStopTicketsModelBuilder {
    //the instance to build
    private NonStopTicketsDataModel nonStopTicketsDataModel;

    /**
     * Default constructor to initialize the instance
     */
    public NonStopTicketsDataModelBuilder() {
        nonStopTicketsDataModel = new NonStopTicketsDataModel();
    }

    /**
     * IATA code of destination city
     */
    public NonStopTicketsDataModelBuilder lED(LinkedHashMap<String, String> lED) {
        nonStopTicketsDataModel.setLED(lED);
        return this;
    }

    /**
     * ticket price (in specified currency)
     */
    public NonStopTicketsDataModelBuilder price(int price) {
        nonStopTicketsDataModel.setPrice(price);
        return this;
    }

    /**
     * IATA code of airline operating the flight
     */
    public NonStopTicketsDataModelBuilder airline(String airline) {
        nonStopTicketsDataModel.setAirline(airline);
        return this;
    }

    /**
     * flight number
     */
    public NonStopTicketsDataModelBuilder flightNumber(int flightNumber) {
        nonStopTicketsDataModel.setFlightNumber(flightNumber);
        return this;
    }

    /**
     * departure date
     */
    public NonStopTicketsDataModelBuilder departureAt(String departureAt) {
        nonStopTicketsDataModel.setDepartureAt(departureAt);
        return this;
    }

    /**
     * return date
     */
    public NonStopTicketsDataModelBuilder returnAt(String returnAt) {
        nonStopTicketsDataModel.setReturnAt(returnAt);
        return this;
    }

    /**
     * date on which the found price expires (UTC+0)
     */
    public NonStopTicketsDataModelBuilder expiresAt(String expiresAt) {
        nonStopTicketsDataModel.setExpiresAt(expiresAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NonStopTicketsDataModel build() {
        return nonStopTicketsDataModel;
    }
}