/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class NonStopTicketsModelBuilder {
    //the instance to build
    private NonStopTicketsModel nonStopTicketsModel;

    /**
     * Default constructor to initialize the instance
     */
    public NonStopTicketsModelBuilder() {
        nonStopTicketsModel = new NonStopTicketsModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public NonStopTicketsModelBuilder success(boolean success) {
        nonStopTicketsModel.setSuccess(success);
        return this;
    }

    /**
     * result of the request; in case of an error is equal to null
     */
    public NonStopTicketsModelBuilder data(LinkedHashMap<String, NonStopTicketsDataModel> data) {
        nonStopTicketsModel.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NonStopTicketsModel build() {
        return nonStopTicketsModel;
    }
}