/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class NonStopTicketsDataModel 
        extends NonStopTicketsModel {
    private static final long serialVersionUID = 5606807326705978709L;
    private LinkedHashMap<String, String> lED;
    private int price;
    private String airline;
    private int flightNumber;
    private String departureAt;
    private String returnAt;
    private String expiresAt;
    /** GETTER
     * IATA code of destination city
     */
    @JsonGetter("LED")
    public LinkedHashMap<String, String> getLED ( ) { 
        return this.lED;
    }
    
    /** SETTER
     * IATA code of destination city
     */
    @JsonSetter("LED")
    public void setLED (LinkedHashMap<String, String> value) { 
        this.lED = value;
    }
 
    /** GETTER
     * ticket price (in specified currency)
     */
    @JsonGetter("price")
    public int getPrice ( ) { 
        return this.price;
    }
    
    /** SETTER
     * ticket price (in specified currency)
     */
    @JsonSetter("price")
    public void setPrice (int value) { 
        this.price = value;
    }
 
    /** GETTER
     * IATA code of airline operating the flight
     */
    @JsonGetter("airline")
    public String getAirline ( ) { 
        return this.airline;
    }
    
    /** SETTER
     * IATA code of airline operating the flight
     */
    @JsonSetter("airline")
    public void setAirline (String value) { 
        this.airline = value;
    }
 
    /** GETTER
     * flight number
     */
    @JsonGetter("flight_number")
    public int getFlightNumber ( ) { 
        return this.flightNumber;
    }
    
    /** SETTER
     * flight number
     */
    @JsonSetter("flight_number")
    public void setFlightNumber (int value) { 
        this.flightNumber = value;
    }
 
    /** GETTER
     * departure date
     */
    @JsonGetter("departure_at")
    public String getDepartureAt ( ) { 
        return this.departureAt;
    }
    
    /** SETTER
     * departure date
     */
    @JsonSetter("departure_at")
    public void setDepartureAt (String value) { 
        this.departureAt = value;
    }
 
    /** GETTER
     * return date
     */
    @JsonGetter("return_at")
    public String getReturnAt ( ) { 
        return this.returnAt;
    }
    
    /** SETTER
     * return date
     */
    @JsonSetter("return_at")
    public void setReturnAt (String value) { 
        this.returnAt = value;
    }
 
    /** GETTER
     * date on which the found price expires (UTC+0)
     */
    @JsonGetter("expires_at")
    public String getExpiresAt ( ) { 
        return this.expiresAt;
    }
    
    /** SETTER
     * date on which the found price expires (UTC+0)
     */
    @JsonSetter("expires_at")
    public void setExpiresAt (String value) { 
        this.expiresAt = value;
    }
 
}
 