/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PopularAirlineRoutesDataModel 
        extends PopularAirlineRoutesModel {
    private static final long serialVersionUID = 4877260978765423448L;
    private String mOWAER;
    /** GETTER
     * popular routes of an airline, sorted by popularity
     */
    @JsonGetter("MOW-AER")
    public String getMOWAER ( ) { 
        return this.mOWAER;
    }
    
    /** SETTER
     * popular routes of an airline, sorted by popularity
     */
    @JsonSetter("MOW-AER")
    public void setMOWAER (String value) { 
        this.mOWAER = value;
    }
 
}
 