/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class PopularAirlineRoutesDataModelBuilder 
        extends PopularAirlineRoutesModelBuilder {
    //the instance to build
    private PopularAirlineRoutesDataModel popularAirlineRoutesDataModel;

    /**
     * Default constructor to initialize the instance
     */
    public PopularAirlineRoutesDataModelBuilder() {
        popularAirlineRoutesDataModel = new PopularAirlineRoutesDataModel();
    }

    /**
     * popular routes of an airline, sorted by popularity
     */
    public PopularAirlineRoutesDataModelBuilder mOWAER(String mOWAER) {
        popularAirlineRoutesDataModel.setMOWAER(mOWAER);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PopularAirlineRoutesDataModel build() {
        return popularAirlineRoutesDataModel;
    }
}