/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class PopularAirlineRoutesModelBuilder {
    //the instance to build
    private PopularAirlineRoutesModel popularAirlineRoutesModel;

    /**
     * Default constructor to initialize the instance
     */
    public PopularAirlineRoutesModelBuilder() {
        popularAirlineRoutesModel = new PopularAirlineRoutesModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public PopularAirlineRoutesModelBuilder success(boolean success) {
        popularAirlineRoutesModel.setSuccess(success);
        return this;
    }

    /**
     * list of popular routes of an airline
     */
    public PopularAirlineRoutesModelBuilder data(LinkedHashMap<String, PopularAirlineRoutesDataModel> data) {
        popularAirlineRoutesModel.setData(data);
        return this;
    }

    /**
     * short description of the error that prevented query completion; for successful queries is equal to null
     */
    public PopularAirlineRoutesModelBuilder error(String error) {
        popularAirlineRoutesModel.setError(error);
        return this;
    }

    /**
     * the airline tickets currency
     */
    public PopularAirlineRoutesModelBuilder currency(String currency) {
        popularAirlineRoutesModel.setCurrency(currency);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PopularAirlineRoutesModel build() {
        return popularAirlineRoutesModel;
    }
}