/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PopularAirlineRoutesModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5026264556724032400L;
    private boolean success;
    private LinkedHashMap<String, PopularAirlineRoutesDataModel> data;
    private String error;
    private String currency;
    /** GETTER
     * true - request is successful, false - the response has error
     */
    @JsonGetter("success")
    public boolean getSuccess ( ) { 
        return this.success;
    }
    
    /** SETTER
     * true - request is successful, false - the response has error
     */
    @JsonSetter("success")
    public void setSuccess (boolean value) { 
        this.success = value;
    }
 
    /** GETTER
     * list of popular routes of an airline
     */
    @JsonGetter("data")
    public LinkedHashMap<String, PopularAirlineRoutesDataModel> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * list of popular routes of an airline
     */
    @JsonSetter("data")
    public void setData (LinkedHashMap<String, PopularAirlineRoutesDataModel> value) { 
        this.data = value;
    }
 
    /** GETTER
     * short description of the error that prevented query completion; for successful queries is equal to null
     */
    @JsonGetter("error")
    public String getError ( ) { 
        return this.error;
    }
    
    /** SETTER
     * short description of the error that prevented query completion; for successful queries is equal to null
     */
    @JsonSetter("error")
    public void setError (String value) { 
        this.error = value;
    }
 
    /** GETTER
     * the airline tickets currency
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * the airline tickets currency
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
}
 