/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class TheCalendarOfPricesForAWeekModelBuilder {
    //the instance to build
    private TheCalendarOfPricesForAWeekModel theCalendarOfPricesForAWeekModel;

    /**
     * Default constructor to initialize the instance
     */
    public TheCalendarOfPricesForAWeekModelBuilder() {
        theCalendarOfPricesForAWeekModel = new TheCalendarOfPricesForAWeekModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public TheCalendarOfPricesForAWeekModelBuilder success(boolean success) {
        theCalendarOfPricesForAWeekModel.setSuccess(success);
        return this;
    }

    /**
     * result of the request; in case of an error is equal to null
     */
    public TheCalendarOfPricesForAWeekModelBuilder data(List<TheCalendarOfPricesForAWeekDataModel> data) {
        theCalendarOfPricesForAWeekModel.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TheCalendarOfPricesForAWeekModel build() {
        return theCalendarOfPricesForAWeekModel;
    }
}