/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class TheCalendarOfPricesForAMonthModelBuilder {
    //the instance to build
    private TheCalendarOfPricesForAMonthModel theCalendarOfPricesForAMonthModel;

    /**
     * Default constructor to initialize the instance
     */
    public TheCalendarOfPricesForAMonthModelBuilder() {
        theCalendarOfPricesForAMonthModel = new TheCalendarOfPricesForAMonthModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public TheCalendarOfPricesForAMonthModelBuilder success(boolean success) {
        theCalendarOfPricesForAMonthModel.setSuccess(success);
        return this;
    }

    /**
     * result of the request; in case of an error is equal to null
     */
    public TheCalendarOfPricesForAMonthModelBuilder data(List<TheCalendarOfPricesForAMonthDatumModel> data) {
        theCalendarOfPricesForAMonthModel.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TheCalendarOfPricesForAMonthModel build() {
        return theCalendarOfPricesForAMonthModel;
    }
}