/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class ThePricesForTheAlternativeDirectionsModelBuilder {
    //the instance to build
    private ThePricesForTheAlternativeDirectionsModel thePricesForTheAlternativeDirectionsModel;

    /**
     * Default constructor to initialize the instance
     */
    public ThePricesForTheAlternativeDirectionsModelBuilder() {
        thePricesForTheAlternativeDirectionsModel = new ThePricesForTheAlternativeDirectionsModel();
    }

    /**
     * the array with info about prices
     */
    public ThePricesForTheAlternativeDirectionsModelBuilder prices(List<ThePricesForTheAlternativeDirectionsPriceModel> prices) {
        thePricesForTheAlternativeDirectionsModel.setPrices(prices);
        return this;
    }

    /**
     * the point of departure
     */
    public ThePricesForTheAlternativeDirectionsModelBuilder origins(List<String> origins) {
        thePricesForTheAlternativeDirectionsModel.setOrigins(origins);
        return this;
    }

    /**
     * if the error "Some error occurred" is returned, so in this area do not have the data in the cache
     */
    public ThePricesForTheAlternativeDirectionsModelBuilder errors(LinkedHashMap<String, ThePricesForTheAlternativeDirectionsErrorsModel> errors) {
        thePricesForTheAlternativeDirectionsModel.setErrors(errors);
        return this;
    }

    /**
     * the point of destination
     */
    public ThePricesForTheAlternativeDirectionsModelBuilder destinations(List<String> destinations) {
        thePricesForTheAlternativeDirectionsModel.setDestinations(destinations);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ThePricesForTheAlternativeDirectionsModel build() {
        return thePricesForTheAlternativeDirectionsModel;
    }
}