/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class ThePricesForTheAirlineTicketsModelBuilder {
    //the instance to build
    private ThePricesForTheAirlineTicketsModel thePricesForTheAirlineTicketsModel;

    /**
     * Default constructor to initialize the instance
     */
    public ThePricesForTheAirlineTicketsModelBuilder() {
        thePricesForTheAirlineTicketsModel = new ThePricesForTheAirlineTicketsModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public ThePricesForTheAirlineTicketsModelBuilder success(boolean success) {
        thePricesForTheAirlineTicketsModel.setSuccess(success);
        return this;
    }

    /**
     * result of the request; in case of an error is equal to null
     */
    public ThePricesForTheAirlineTicketsModelBuilder data(List<ThePricesForTheAirlineTicketsDatumModel> data) {
        thePricesForTheAirlineTicketsModel.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ThePricesForTheAirlineTicketsModel build() {
        return thePricesForTheAirlineTicketsModel;
    }
}