/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ThePopularDirectionsFromACityModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5731461553012646398L;
    private boolean success;
    private LinkedHashMap<String, ThePopularDirectionsFromACityDataModel> data;
    private String currency;
    private String error;
    /** GETTER
     * true - request is successful, false - the response has error
     */
    @JsonGetter("success")
    public boolean getSuccess ( ) { 
        return this.success;
    }
    
    /** SETTER
     * true - request is successful, false - the response has error
     */
    @JsonSetter("success")
    public void setSuccess (boolean value) { 
        this.success = value;
    }
 
    /** GETTER
     * result of the request; in case of an error is equal to null
     */
    @JsonGetter("data")
    public LinkedHashMap<String, ThePopularDirectionsFromACityDataModel> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * result of the request; in case of an error is equal to null
     */
    @JsonSetter("data")
    public void setData (LinkedHashMap<String, ThePopularDirectionsFromACityDataModel> value) { 
        this.data = value;
    }
 
    /** GETTER
     * currency of response
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * currency of response
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * short description of the error that prevented request completion; for successful request is equal to null
     */
    @JsonGetter("error")
    public String getError ( ) { 
        return this.error;
    }
    
    /** SETTER
     * short description of the error that prevented request completion; for successful request is equal to null
     */
    @JsonSetter("error")
    public void setError (String value) { 
        this.error = value;
    }
 
}
 