/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class ThePricesForTheAirlineTicketsDatumModelBuilder 
        extends ThePricesForTheAirlineTicketsModelBuilder {
    //the instance to build
    private ThePricesForTheAirlineTicketsDatumModel thePricesForTheAirlineTicketsDatumModel;

    /**
     * Default constructor to initialize the instance
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder() {
        thePricesForTheAirlineTicketsDatumModel = new ThePricesForTheAirlineTicketsDatumModel();
    }

    /**
     * false — all the prices, true — just the prices, found using the partner marker (recommended)
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder showToAffiliates(boolean showToAffiliates) {
        thePricesForTheAirlineTicketsDatumModel.setShowToAffiliates(showToAffiliates);
        return this;
    }

    /**
     * the flight class. 0 — the economy class, 1 — the business class, 2 — the first class.
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder tripClass(String tripClass) {
        thePricesForTheAirlineTicketsDatumModel.setTripClass(tripClass);
        return this;
    }

    /**
     * the point of departure
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder origin(String origin) {
        thePricesForTheAirlineTicketsDatumModel.setOrigin(origin);
        return this;
    }

    /**
     * the point of destination
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder destination(String destination) {
        thePricesForTheAirlineTicketsDatumModel.setDestination(destination);
        return this;
    }

    /**
     * the date of departure
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder departDate(String departDate) {
        thePricesForTheAirlineTicketsDatumModel.setDepartDate(departDate);
        return this;
    }

    /**
     * the date of return
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder returnDate(String returnDate) {
        thePricesForTheAirlineTicketsDatumModel.setReturnDate(returnDate);
        return this;
    }

    /**
     * the number of transfers
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder numberOfChanges(int numberOfChanges) {
        thePricesForTheAirlineTicketsDatumModel.setNumberOfChanges(numberOfChanges);
        return this;
    }

    /**
     * the cost of a flight, in the currency specified
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder value(String value) {
        thePricesForTheAirlineTicketsDatumModel.setValue(value);
        return this;
    }

    /**
     * the time and the date, for which a ticket was found
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder foundAt(String foundAt) {
        thePricesForTheAirlineTicketsDatumModel.setFoundAt(foundAt);
        return this;
    }

    /**
     * the distance between the point of departure and the point of destination
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder distance(String distance) {
        thePricesForTheAirlineTicketsDatumModel.setDistance(distance);
        return this;
    }

    /**
     * the actuality of an offer
     */
    public ThePricesForTheAirlineTicketsDatumModelBuilder actual(boolean actual) {
        thePricesForTheAirlineTicketsDatumModel.setActual(actual);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ThePricesForTheAirlineTicketsDatumModel build() {
        return thePricesForTheAirlineTicketsDatumModel;
    }
}