/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ThePopularDirectionsFromACityDataModel 
        extends ThePopularDirectionsFromACityModel {
    private static final long serialVersionUID = 5071683707432847222L;
    private LinkedHashMap<String, ThePopularDirectionsFromACityAERModel> aER;
    /** GETTER
     * the point of destination
     */
    @JsonGetter("AER")
    public LinkedHashMap<String, ThePopularDirectionsFromACityAERModel> getAER ( ) { 
        return this.aER;
    }
    
    /** SETTER
     * the point of destination
     */
    @JsonSetter("AER")
    public void setAER (LinkedHashMap<String, ThePopularDirectionsFromACityAERModel> value) { 
        this.aER = value;
    }
 
}
 