/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class ThePopularDirectionsFromACityModelBuilder {
    //the instance to build
    private ThePopularDirectionsFromACityModel thePopularDirectionsFromACityModel;

    /**
     * Default constructor to initialize the instance
     */
    public ThePopularDirectionsFromACityModelBuilder() {
        thePopularDirectionsFromACityModel = new ThePopularDirectionsFromACityModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public ThePopularDirectionsFromACityModelBuilder success(boolean success) {
        thePopularDirectionsFromACityModel.setSuccess(success);
        return this;
    }

    /**
     * result of the request; in case of an error is equal to null
     */
    public ThePopularDirectionsFromACityModelBuilder data(LinkedHashMap<String, ThePopularDirectionsFromACityDataModel> data) {
        thePopularDirectionsFromACityModel.setData(data);
        return this;
    }

    /**
     * currency of response
     */
    public ThePopularDirectionsFromACityModelBuilder currency(String currency) {
        thePopularDirectionsFromACityModel.setCurrency(currency);
        return this;
    }

    /**
     * short description of the error that prevented request completion; for successful request is equal to null
     */
    public ThePopularDirectionsFromACityModelBuilder error(String error) {
        thePopularDirectionsFromACityModel.setError(error);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ThePopularDirectionsFromACityModel build() {
        return thePopularDirectionsFromACityModel;
    }
}