/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ThePricesForTheAlternativeDirectionsModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5254679626996669158L;
    private List<ThePricesForTheAlternativeDirectionsPriceModel> prices;
    private List<String> origins;
    private LinkedHashMap<String, ThePricesForTheAlternativeDirectionsErrorsModel> errors;
    private List<String> destinations;
    /** GETTER
     * the array with info about prices
     */
    @JsonGetter("prices")
    public List<ThePricesForTheAlternativeDirectionsPriceModel> getPrices ( ) { 
        return this.prices;
    }
    
    /** SETTER
     * the array with info about prices
     */
    @JsonSetter("prices")
    public void setPrices (List<ThePricesForTheAlternativeDirectionsPriceModel> value) { 
        this.prices = value;
    }
 
    /** GETTER
     * the point of departure
     */
    @JsonGetter("origins")
    public List<String> getOrigins ( ) { 
        return this.origins;
    }
    
    /** SETTER
     * the point of departure
     */
    @JsonSetter("origins")
    public void setOrigins (List<String> value) { 
        this.origins = value;
    }
 
    /** GETTER
     * if the error "Some error occurred" is returned, so in this area do not have the data in the cache
     */
    @JsonGetter("errors")
    public LinkedHashMap<String, ThePricesForTheAlternativeDirectionsErrorsModel> getErrors ( ) { 
        return this.errors;
    }
    
    /** SETTER
     * if the error "Some error occurred" is returned, so in this area do not have the data in the cache
     */
    @JsonSetter("errors")
    public void setErrors (LinkedHashMap<String, ThePricesForTheAlternativeDirectionsErrorsModel> value) { 
        this.errors = value;
    }
 
    /** GETTER
     * the point of destination
     */
    @JsonGetter("destinations")
    public List<String> getDestinations ( ) { 
        return this.destinations;
    }
    
    /** SETTER
     * the point of destination
     */
    @JsonSetter("destinations")
    public void setDestinations (List<String> value) { 
        this.destinations = value;
    }
 
}
 