/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ThePricesForTheAlternativeDirectionsErrorsModel 
        extends ThePricesForTheAlternativeDirectionsModel {
    private static final long serialVersionUID = 5512892267507771849L;
    private Object amadeus;
    /** GETTER
     * if the error "Some error occurred" is returned, so in this area do not have the data in the cache
     */
    @JsonGetter("amadeus")
    public Object getAmadeus ( ) { 
        return this.amadeus;
    }
    
    /** SETTER
     * if the error "Some error occurred" is returned, so in this area do not have the data in the cache
     */
    @JsonSetter("amadeus")
    public void setAmadeus (Object value) { 
        this.amadeus = value;
    }
 
}
 