/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class ThePopularDirectionsFromACityDataModelBuilder 
        extends ThePopularDirectionsFromACityModelBuilder {
    //the instance to build
    private ThePopularDirectionsFromACityDataModel thePopularDirectionsFromACityDataModel;

    /**
     * Default constructor to initialize the instance
     */
    public ThePopularDirectionsFromACityDataModelBuilder() {
        thePopularDirectionsFromACityDataModel = new ThePopularDirectionsFromACityDataModel();
    }

    /**
     * the point of destination
     */
    public ThePopularDirectionsFromACityDataModelBuilder aER(LinkedHashMap<String, ThePopularDirectionsFromACityAERModel> aER) {
        thePopularDirectionsFromACityDataModel.setAER(aER);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ThePopularDirectionsFromACityDataModel build() {
        return thePopularDirectionsFromACityDataModel;
    }
}