/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class ThePricesForTheAlternativeDirectionsErrorsModelBuilder 
        extends ThePricesForTheAlternativeDirectionsModelBuilder {
    //the instance to build
    private ThePricesForTheAlternativeDirectionsErrorsModel thePricesForTheAlternativeDirectionsErrorsModel;

    /**
     * Default constructor to initialize the instance
     */
    public ThePricesForTheAlternativeDirectionsErrorsModelBuilder() {
        thePricesForTheAlternativeDirectionsErrorsModel = new ThePricesForTheAlternativeDirectionsErrorsModel();
    }

    /**
     * if the error "Some error occurred" is returned, so in this area do not have the data in the cache
     */
    public ThePricesForTheAlternativeDirectionsErrorsModelBuilder amadeus(Object amadeus) {
        thePricesForTheAlternativeDirectionsErrorsModel.setAmadeus(amadeus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ThePricesForTheAlternativeDirectionsErrorsModel build() {
        return thePricesForTheAlternativeDirectionsErrorsModel;
    }
}