/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class ThePopularDirectionsFromACityAERModelBuilder 
        extends ThePopularDirectionsFromACityDataModelBuilder {
    //the instance to build
    private ThePopularDirectionsFromACityAERModel thePopularDirectionsFromACityAERModel;

    /**
     * Default constructor to initialize the instance
     */
    public ThePopularDirectionsFromACityAERModelBuilder() {
        thePopularDirectionsFromACityAERModel = new ThePopularDirectionsFromACityAERModel();
    }

    /**
     * the point of departure
     */
    public ThePopularDirectionsFromACityAERModelBuilder origin(String origin) {
        thePopularDirectionsFromACityAERModel.setOrigin(origin);
        return this;
    }

    /**
     * the point of destination
     */
    public ThePopularDirectionsFromACityAERModelBuilder destination(String destination) {
        thePopularDirectionsFromACityAERModel.setDestination(destination);
        return this;
    }

    /**
     * the cost of a flight, in the currency specified
     */
    public ThePopularDirectionsFromACityAERModelBuilder price(int price) {
        thePopularDirectionsFromACityAERModel.setPrice(price);
        return this;
    }

    /**
     * the number of direct
     */
    public ThePopularDirectionsFromACityAERModelBuilder transfers(int transfers) {
        thePopularDirectionsFromACityAERModel.setTransfers(transfers);
        return this;
    }

    /**
     * IATA of airline
     */
    public ThePopularDirectionsFromACityAERModelBuilder airline(String airline) {
        thePopularDirectionsFromACityAERModel.setAirline(airline);
        return this;
    }

    /**
     * flight number
     */
    public ThePopularDirectionsFromACityAERModelBuilder flightNumber(int flightNumber) {
        thePopularDirectionsFromACityAERModel.setFlightNumber(flightNumber);
        return this;
    }

    /**
     * the flight number
     */
    public ThePopularDirectionsFromACityAERModelBuilder departureAt(String departureAt) {
        thePopularDirectionsFromACityAERModel.setDepartureAt(departureAt);
        return this;
    }

    /**
     * the date of return
     */
    public ThePopularDirectionsFromACityAERModelBuilder returnAt(String returnAt) {
        thePopularDirectionsFromACityAERModel.setReturnAt(returnAt);
        return this;
    }

    /**
     * date on which the found price expires (UTC+0)
     */
    public ThePopularDirectionsFromACityAERModelBuilder expiresAt(String expiresAt) {
        thePopularDirectionsFromACityAERModel.setExpiresAt(expiresAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ThePopularDirectionsFromACityAERModel build() {
        return thePopularDirectionsFromACityAERModel;
    }
}