/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TicketsForEachDayOfMonthDataModel 
        extends TicketsForEachDayOfMonthModel {
    private static final long serialVersionUID = 4911564956917671923L;
    private String origin;
    private String destination;
    private int price;
    private int transfers;
    private String airline;
    private int flightNumber;
    private String departureAt;
    private String returnAt;
    private String expiresAt;
    /** GETTER
     * IATA code of departure city
     */
    @JsonGetter("origin")
    public String getOrigin ( ) { 
        return this.origin;
    }
    
    /** SETTER
     * IATA code of departure city
     */
    @JsonSetter("origin")
    public void setOrigin (String value) { 
        this.origin = value;
    }
 
    /** GETTER
     * IATA code of destination city
     */
    @JsonGetter("destination")
    public String getDestination ( ) { 
        return this.destination;
    }
    
    /** SETTER
     * IATA code of destination city
     */
    @JsonSetter("destination")
    public void setDestination (String value) { 
        this.destination = value;
    }
 
    /** GETTER
     * ticket price in the specified currency
     */
    @JsonGetter("price")
    public int getPrice ( ) { 
        return this.price;
    }
    
    /** SETTER
     * ticket price in the specified currency
     */
    @JsonSetter("price")
    public void setPrice (int value) { 
        this.price = value;
    }
 
    /** GETTER
     * number of stops
     */
    @JsonGetter("transfers")
    public int getTransfers ( ) { 
        return this.transfers;
    }
    
    /** SETTER
     * number of stops
     */
    @JsonSetter("transfers")
    public void setTransfers (int value) { 
        this.transfers = value;
    }
 
    /** GETTER
     * IATA code of airline
     */
    @JsonGetter("airline")
    public String getAirline ( ) { 
        return this.airline;
    }
    
    /** SETTER
     * IATA code of airline
     */
    @JsonSetter("airline")
    public void setAirline (String value) { 
        this.airline = value;
    }
 
    /** GETTER
     * flight number
     */
    @JsonGetter("flight_number")
    public int getFlightNumber ( ) { 
        return this.flightNumber;
    }
    
    /** SETTER
     * flight number
     */
    @JsonSetter("flight_number")
    public void setFlightNumber (int value) { 
        this.flightNumber = value;
    }
 
    /** GETTER
     * departure Date
     */
    @JsonGetter("departure_at")
    public String getDepartureAt ( ) { 
        return this.departureAt;
    }
    
    /** SETTER
     * departure Date
     */
    @JsonSetter("departure_at")
    public void setDepartureAt (String value) { 
        this.departureAt = value;
    }
 
    /** GETTER
     * return Date
     */
    @JsonGetter("return_at")
    public String getReturnAt ( ) { 
        return this.returnAt;
    }
    
    /** SETTER
     * return Date
     */
    @JsonSetter("return_at")
    public void setReturnAt (String value) { 
        this.returnAt = value;
    }
 
    /** GETTER
     * when the found price expires (UTC+0)
     */
    @JsonGetter("expires_at")
    public String getExpiresAt ( ) { 
        return this.expiresAt;
    }
    
    /** SETTER
     * when the found price expires (UTC+0)
     */
    @JsonSetter("expires_at")
    public void setExpiresAt (String value) { 
        this.expiresAt = value;
    }
 
}
 