/*
 * TravelpayoutsDataAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package com.travelpayouts.api.models;

import java.util.*;

public class TicketsForEachDayOfMonthModelBuilder {
    //the instance to build
    private TicketsForEachDayOfMonthModel ticketsForEachDayOfMonthModel;

    /**
     * Default constructor to initialize the instance
     */
    public TicketsForEachDayOfMonthModelBuilder() {
        ticketsForEachDayOfMonthModel = new TicketsForEachDayOfMonthModel();
    }

    /**
     * true - request is successful, false - the response has error
     */
    public TicketsForEachDayOfMonthModelBuilder success(boolean success) {
        ticketsForEachDayOfMonthModel.setSuccess(success);
        return this;
    }

    /**
     * result of the request; in case of an error is equal to null
     */
    public TicketsForEachDayOfMonthModelBuilder data(LinkedHashMap<String, TicketsForEachDayOfMonthDataModel> data) {
        ticketsForEachDayOfMonthModel.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TicketsForEachDayOfMonthModel build() {
        return ticketsForEachDayOfMonthModel;
    }
}